# language: node_js

# node_js:
#   - node
# cache:
#   directories:
#     - "node_modules"
    
# install:
#     - npm install
#     - npm ci

# script:
#   - npm run test:coveralls

language: node_js

node_js:
  - node
cache:
  directories:
    - "node_modules"
    
install:
    - npm install
    - npm ci

script:
  - npm test
